task at hand
data - filtering
deduplicate 
need to integrate A6000 as a new kernal

spark session maybe
fasttext - optimised for non gpu, language parser for non gpu

In [1]:
import pandas as pd

In [2]:
#Source data 
L_DATA = "../data"
G_DATA = "/DATA/BLF/climatechange/"

In [3]:
original = pd.read_feather(f"{G_DATA}/ClimateChange-experimental-full.feather")

In [4]:
#original.head()

,id,created_at,u_id,u_name,u_screen_name,u_created_at,u_lang,u_profile_desc,u_url,full_tweet_text,rt_id,rt_created_at,rtu_id,rtu_name,rtu_screen_name,rtu_created_at,rtu_lang,rtu_profile_desc,rtu_url,tweet_hash
0,ID_1264099683011616768,Sat May 23 07:43:44 +0000 2020,4885898638,Be More Girl,hellobemoregirl,Sun Feb 07 21:06:59 +0000 2016,NaN,Creative brand strategist. Blogger. Championin...,http://uk.linkedin.com/in/sharonbrunt,Did you know it's #MentalHealthAwarenessWeek? ...,ID_1264088752424734720,Sat May 23 07:00:18 +0000 2020,1.582174e+07,The Climate Coalition,TheCCoalition,Tue Aug 12 12:48:56 +0000 2008,NaN,We're the largest group of people in the UK de...,https://www.theclimatecoalition.org/show-the-love,22e6e47dc0c2bc9fbc1a7789696c6726
1,ID_1264099691144400897,Sat May 23 07:43:46 +0000 2020,3201031625,Joseph Garnier ü§ñüß†üñ•Ô∏è,Joseph_Garnier,Fri Apr 24 12:32:31 +0000 2015,NaN,ü§ñüß† PhD student in #AI (affective computing). üî¨üì∞,None,@Jiemb1 @nbonneel qui ont un effet b√©n√©fique s...,None,Sat May 23 07:00:18 +0000 2020,NaN,None,None,None,NaN,None,None,8a26ca54b377aedd1b3ba362117082a1
2,ID_1264099691744169984,Sat May 23 07:43:47 +0000 2020,2887452442,Lanre üëë,femirewaju,Fri Nov 21 22:23:14 +0000 2014,NaN,Chartered Accountant. Anti philistine. Cassava...,None,@yourijebubabe @anu4real @meccuno @hon_ags @me...,None,Sat May 23 07:00:18 +0000 2020,NaN,None,None,None,NaN,None,None,8e4e77e1f94523737fc2d21be8038f10
3,ID_1264099696068476928,Sat May 23 07:43:48 +0000 2020,1867999656,Lukas L√ºtke‚ö°,LUKASLUETKE,Sun Sep 15 14:55:27 +0000 2013,NaN,None,None,Seit einigen Tagen werden wir mit Beleidigunge...,ID_1263913998413684736,Fri May 22 19:25:54 +0000 2020,3.232961e+09,Ende Gel√§nde,Ende__Gelaende,Mon May 04 08:39:42 +0000 2015,NaN,Massenhafter Ungehorsam f√ºr den sofortigen Koh...,http://xn--ende-gelnde-s8a.org,9870bdb0fa360aae82b81541ea023e64
4,ID_1264099713202229255,Sat May 23 07:43:52 +0000 2020,1241421060521758720,Heartbreak,Herzbrech,Sat Mar 21 17:47:24 +0000 2020,NaN,Kneipe im Tal der Ahnungslosen,http://Facebook.com/Herzbrech,Seit einigen Tagen werden wir mit Beleidigunge...,ID_1263913998413684736,Fri May 22 19:25:54 +0000 2020,3.232961e+09,Ende Gel√§nde,Ende__Gelaende,Mon May 04 08:39:42 +0000 2015,NaN,Massenhafter Ungehorsam f√ºr den sofortigen Koh...,http://xn--ende-gelnde-s8a.org,9870bdb0fa360aae82b81541ea023e64

In [5]:
#sample df contains 10000 rows
df = original.sample(n=10000)
df.reset_index(drop=True, inplace =True)

In [6]:
df.head()

,id,created_at,u_id,u_name,u_screen_name,u_created_at,u_lang,u_profile_desc,u_url,full_tweet_text,rt_id,rt_created_at,rtu_id,rtu_name,rtu_screen_name,rtu_created_at,rtu_lang,rtu_profile_desc,rtu_url,tweet_hash
0,ID_1275749328523493377,Wed Jun 24 11:15:16 +0000 2020,1134574527738982401,Carla Martins,CarlaMartins_BR,Fri May 31 21:37:01 +0000 2019,NaN,GCRF Visiting Fellow at @OfficialUoM. Research...,None,Theme 4 - new video!! Amazing interview betwee...,None,Tue Jun 23 23:22:14 +0000 2020,NaN,None,None,None,NaN,None,None,bf38020ec745491b99561d24228eeb46
1,ID_1283105121824583680,Tue Jul 14 18:24:34 +0000 2020,782261367583739904,Zachary Getsingerüá∫üá∏,ZachG444,Sat Oct 01 16:50:18 +0000 2016,NaN,Kings #1 dishwasher,None,Humanity is doomed.,ID_1283089608830603266,Tue Jul 14 17:22:56 +0000 2020,23022687.0,Ted Cruz,tedcruz,Fri Mar 06 03:20:20 +0000 2009,NaN,"Father of two, @heidiscruz's husband, fighter ...",http://www.tedcruz.org,55e67015c1de6e86e9afeaa2f4e77512
2,ID_1278984747100889089,Fri Jul 03 09:31:40 +0000 2020,1223244941859618819,Andria Nicodemou,AndriaBSC,Fri Jan 31 14:01:53 +0000 2020,NaN,Science communication specialist at @BSC_CNS. ...,None,High temperatures are expected in eastern and ...,None,Fri Jul 03 09:16:14 +0000 2020,NaN,None,None,None,NaN,None,None,f01e66e36880379f30912e9beb59150d
3,ID_1299255219973484545,Fri Aug 28 07:59:18 +0000 2020,707781288149786624,Majic Mirror,majicmirror16,Thu Mar 10 04:13:03 +0000 2016,NaN,Reflecting magically,None,#RT @davidhogg111: Trumps about to take climat...,None,Fri Aug 28 07:54:28 +0000 2020,NaN,None,None,None,NaN,None,None,b47a8d627d2b6bc69c92a6d2122c4873
4,ID_1283814431542120449,Thu Jul 16 17:23:07 +0000 2020,813377336,tom bartell,tombartell1,Sun Sep 09 15:49:48 +0000 2012,NaN,father of 4 married 24 years and counting like...,None,Whenever a liberal claims to ‚Äúbelieve in scien...,ID_1283784256079241219,Thu Jul 16 15:23:12 +0000 2020,334715818.0,Buck Sexton,BuckSexton,Wed Jul 13 15:14:49 +0000 2011,NaN,Host of The Buck Sexton Show; Former CIA Analy...,http://bucksexton.com,59539162ee05d75f0bccbe811b09cf2c

In [7]:
# for any ICWSM we need timestamp, uid, uname,tweet txt, retweetid, retweetuid, twitter hash
#for Josh , please check if columns selected are right

In [8]:
df.columns

Index(['id', 'created_at', 'u_id', 'u_name', 'u_screen_name', 'u_created_at',
       'u_lang', 'u_profile_desc', 'u_url', 'full_tweet_text', 'rt_id',
       'rt_created_at', 'rtu_id', 'rtu_name', 'rtu_screen_name',
       'rtu_created_at', 'rtu_lang', 'rtu_profile_desc', 'rtu_url',
       'tweet_hash'],
      dtype='object')

In [9]:
df = df[['id','created_at','u_id','u_name','full_tweet_text','rt_id','rt_created_at','rtu_id','rtu_name','tweet_hash']]

In [10]:
df

,id,created_at,u_id,u_name,full_tweet_text,rt_id,rt_created_at,rtu_id,rtu_name,tweet_hash
0,ID_1275749328523493377,Wed Jun 24 11:15:16 +0000 2020,1134574527738982401,Carla Martins,Theme 4 - new video!! Amazing interview betwee...,None,Tue Jun 23 23:22:14 +0000 2020,NaN,None,bf38020ec745491b99561d24228eeb46
1,ID_1283105121824583680,Tue Jul 14 18:24:34 +0000 2020,782261367583739904,Zachary Getsingerüá∫üá∏,Humanity is doomed.,ID_1283089608830603266,Tue Jul 14 17:22:56 +0000 2020,2.302269e+07,Ted Cruz,55e67015c1de6e86e9afeaa2f4e77512
2,ID_1278984747100889089,Fri Jul 03 09:31:40 +0000 2020,1223244941859618819,Andria Nicodemou,High temperatures are expected in eastern and ...,None,Fri Jul 03 09:16:14 +0000 2020,NaN,None,f01e66e36880379f30912e9beb59150d
3,ID_1299255219973484545,Fri Aug 28 07:59:18 +0000 2020,707781288149786624,Majic Mirror,#RT @davidhogg111: Trumps about to take climat...,None,Fri Aug 28 07:54:28 +0000 2020,NaN,None,b47a8d627d2b6bc69c92a6d2122c4873
4,ID_1283814431542120449,Thu Jul 16 17:23:07 +0000 2020,813377336,tom bartell,Whenever a liberal claims to ‚Äúbelieve in scien...,ID_1283784256079241219,Thu Jul 16 15:23:12 +0000 2020,3.347158e+08,Buck Sexton,59539162ee05d75f0bccbe811b09cf2c
...,...,...,...,...,...,...,...,...,...,...
9995,ID_1304927535604674560,Sat Sep 12 23:39:03 +0000 2020,1249900464466001923,dyta,"Hey, Governor Newsom, why does ‚Äúclimate change...",ID_1304834079863443458,Sat Sep 12 17:27:41 +0000 2020,7.852330e+07,James Woods,3d2fb6abe44af256930a7922f2c6f4f9
9996,ID_1304569279422046214,Fri Sep 11 23:55:28 +0000 2020,2817820231,üé¨Xanthanüé• üò∑,"Listen, I'm a firm believer in climate change....",ID_1304557475392151553,Fri Sep 11 23:08:34 +0000 2020,1.248206e+18,LÕÉÕëÃàoÃãÃµÃºÃ§ÃªÕôÃ≥Ã≤-ÃΩÕÇÃÜÃäÕ£ÃëÃöÃ∫ÕïÃ≠ÃôPÃäÃ®ÃüÃôiÕóÕ¨ÃÜÃåÕåÕØÃ±nÃªÃ§ÕçgÕ≠Ãã,f39956ef4d1947f0218ac1869194bd60
9997,ID_1278009665385725953,Tue Jun 30 16:57:03 +0000 2020,373334462,üèÄ üá¶üá∫ Bob Mann üá¶üá∫ üèÄ,"On Behalf Of Environmentalists, I Apologize Fo...",ID_1278004295657385985,Tue Jun 30 16:35:42 +0000 2020,8.889127e+08,Timjbo üá¶üá∫ ‚òî,d39438ff7b6a9bed368bd7467973fab6
9998,ID_1279781012923449346,Sun Jul 05 14:15:45 +0000 2020,869329760706592768,Wendy Squilliams,Did you know that over 90% of climate scientis...,ID_1279378054549250059,Sat Jul 04 11:34:32 +0000 2020,9.562501e+17,Ben See,137b1ede5f72af77ee3bbf59d4caacc1
9999,ID_1315847618275102720,Tue Oct 13 02:51:34 +0000 2020,1129281854576574464,"Be Ethical,Civilized & Competitive",Institutions like @NobelPrize;@NoblewomenNetw;...,None,Fri Oct 09 22:30:00 +0000 2020,NaN,None,57fcb6fbea94d3c45c5c9a4c19d96d3c

In [11]:
import preprocessing as pre

In [12]:
module = dir(pre)

In [13]:
print(module)

['Language', 'LanguageDetector', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'abbr_dict', 'clean_tweet', 'detect', 'emoji_pattern', 'extraChar', 'get_nlp', 'is_english', 'language_detector', 'my_nlp', 're', 'removeRT', 'removeTags', 'removeTagsFromStart', 'spacy', 'special']

In [14]:
df['timestamp_created_at'] = pd.to_datetime(df['created_at'])
df['timestamp_rt_created_at'] = pd.to_datetime(df['rt_created_at'])

In [15]:
df['full_tweet_text'] = df['full_tweet_text'].apply(lambda x: pre.removeRT(x))

In [16]:
df['full_tweet_text'] = df['full_tweet_text'].apply(lambda x: pre.clean_tweet(x,True))